
CREATE TABLE "app_rd_dip" (
	"no" VARCHAR(20) NOT NULL COLLATE 'French_CI_AS',
	"ingredients" VARCHAR(max) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"pao_enabled" TINYINT NULL DEFAULT NULL,
	"pao" INT NULL DEFAULT NULL,
	"category" VARCHAR(20) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"status" TINYINT NULL DEFAULT NULL,
	"dip_no" VARCHAR(10) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"dip_version" VARCHAR(5) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"mode_emploi" VARCHAR(max) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"precautions" VARCHAR(max) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"precautions_etiquette" VARCHAR(max) NULL DEFAULT NULL COLLATE 'French_CI_AS'
)
;


CREATE TABLE "erp_vrac_support" (
	"SKU" NVARCHAR(20) NOT NULL COLLATE 'French_CI_AS',
	"LOT" NVARCHAR(20) NOT NULL COLLATE 'French_CI_AS',
	"SLO" NVARCHAR(9) NOT NULL COLLATE 'French_CI_AS',
	"created_at" DATETIME2(7) NULL DEFAULT NULL,
	"dlu" DATETIME2(7) NULL DEFAULT NULL,
	"dlu_management" NUMERIC(3,0) NULL DEFAULT NULL,
	"qty" FLOAT NULL DEFAULT NULL,
	"origin" NVARCHAR(20) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"ordre_fab" NVARCHAR(20) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"declar_prod" NVARCHAR(20) NULL DEFAULT NULL COLLATE 'French_CI_AS'
)
;

CREATE TABLE "pos_vrac" (
	"no" NVARCHAR(20) NOT NULL COLLATE 'French_CI_AS',
	"vrac_no" NVARCHAR(20) NOT NULL COLLATE 'French_CI_AS',
	"rd_no" VARCHAR(20) NULL DEFAULT NULL COLLATE 'French_CI_AS'
)
;

CREATE TABLE "pos_vrac_devices" (
	"pos" VARCHAR(10) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"device" VARCHAR(50) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"ip" VARCHAR(50) NULL DEFAULT NULL COLLATE 'French_CI_AS'
)
;


CREATE TABLE "pos_vrac_support" (
	"id" INT NOT NULL,
	"pos" NVARCHAR(10) NOT NULL COLLATE 'French_CI_AS',
	"device" NVARCHAR(50) NOT NULL COLLATE 'French_CI_AS',
	"vrac_no" NVARCHAR(20) NOT NULL COLLATE 'French_CI_AS',
	"lot" NVARCHAR(50) NOT NULL COLLATE 'French_CI_AS',
	"slot" NVARCHAR(20) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"scan_date" DATETIME NULL DEFAULT NULL,
	PRIMARY KEY ("id")
)
;


CREATE TABLE "products" (
	"no" NVARCHAR(20) NOT NULL COLLATE 'French_CI_AS',
	"description" NVARCHAR(50) NOT NULL COLLATE 'French_CI_AS',
	"description1" NVARCHAR(50) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"description2" NVARCHAR(50) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"description1_en" NVARCHAR(50) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"description2_en" NVARCHAR(50) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"scientific_description" NVARCHAR(200) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"item_category_code" NVARCHAR(5) NOT NULL COLLATE 'French_CI_AS',
	"item_type" NVARCHAR(5) NOT NULL COLLATE 'French_CI_AS',
	"item_family" NVARCHAR(20) NOT NULL COLLATE 'French_CI_AS',
	"mp_ref" NVARCHAR(20) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"pf_ref" NVARCHAR(20) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"capacity" FLOAT NULL DEFAULT NULL,
	"capacity_unit" NVARCHAR(5) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"capacity_ref" FLOAT NULL DEFAULT NULL,
	"capacity_unit_ref" NVARCHAR(5) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"weight" FLOAT NOT NULL,
	"unit_price" NVARCHAR(10) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"free" FLOAT NULL DEFAULT NULL,
	"price_incl_tax" NVARCHAR(7) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"cost" NVARCHAR(12) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"eco_part" FLOAT NOT NULL,
	"item_family_description_no" NVARCHAR(40) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"item_family_description" NVARCHAR(80) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"item_subfamily_description_no" NVARCHAR(40) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"item_subfamily_description" NVARCHAR(80) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"status" NVARCHAR(16) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"status_no" NUMERIC(3,0) NOT NULL,
	"hidden" FLOAT NULL DEFAULT NULL,
	"priority" FLOAT NULL DEFAULT NULL,
	"tax_percent" NVARCHAR(7) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"custom_family" NVARCHAR(12) NOT NULL COLLATE 'French_CI_AS',
	"old_family_no" NVARCHAR(40) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"old_subfamily_no" NVARCHAR(40) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"density" NVARCHAR(7) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"variant" FLOAT NOT NULL,
	"combusting_point" NUMERIC(5,0) NOT NULL,
	"base_units" NVARCHAR(10) NOT NULL COLLATE 'French_CI_AS',
	"vendor" NVARCHAR(30) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"vendor_name" NVARCHAR(35) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"vendors" NVARCHAR(4000) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"container_code" NVARCHAR(120) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"cosmetic" FLOAT NULL DEFAULT NULL,
	"customs_no" NVARCHAR(12) NOT NULL COLLATE 'French_CI_AS',
	"bio_qualification" FLOAT NULL DEFAULT NULL,
	"bio_qualification_value" NVARCHAR(123) NOT NULL COLLATE 'French_CI_AS',
	"lot_vendor_control" FLOAT NULL DEFAULT NULL,
	"temp_sensibility" FLOAT NULL DEFAULT NULL,
	"microbio_sensibility" FLOAT NULL DEFAULT NULL,
	"conservation_delay" FLOAT NULL DEFAULT NULL,
	"bio_food" FLOAT NULL DEFAULT NULL,
	"bio" FLOAT NULL DEFAULT NULL,
	"fabric_management" FLOAT NULL DEFAULT NULL,
	"lot_economic" FLOAT NULL DEFAULT NULL,
	"lot_tech" FLOAT NULL DEFAULT NULL,
	"unit_qty" FLOAT NULL DEFAULT NULL,
	"pav_type" NVARCHAR(120) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"pav_qty" FLOAT NULL DEFAULT NULL,
	"dlu_management" FLOAT NULL DEFAULT NULL,
	"lot_enabled" FLOAT NULL DEFAULT NULL,
	"lot_family_code" NVARCHAR(20) NOT NULL COLLATE 'French_CI_AS',
	"REAPRO_VALUE" NVARCHAR(14) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"ACCOUNTING_CODE" NVARCHAR(10) NOT NULL COLLATE 'French_CI_AS',
	"NEGOTIATION" FLOAT NULL DEFAULT NULL,
	"PROTOCOL_NO" NVARCHAR(20) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"CMJ" FLOAT NULL DEFAULT NULL,
	"LAST_PURCH_PRICE" NVARCHAR(12) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"updated_at" NVARCHAR(19) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"PLANNER" NVARCHAR(5) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"LINKED_NO" NVARCHAR(20) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"PF" NVARCHAR(4000) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"bom_mp_ref" NVARCHAR(20) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"etiq" NVARCHAR(4000) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"sold_pos" NVARCHAR(4000) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"PIC_NO" NVARCHAR(20) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"PIC" FLOAT NULL DEFAULT NULL,
	"PIC_LAST_MONTH" FLOAT NULL DEFAULT NULL,
	"ITMREF_0" NVARCHAR(20) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"ORIGINE" NVARCHAR(4000) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"COMMENT_NO" NVARCHAR(80) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"comment_rtf" NVARCHAR(4000) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	"comment" NVARCHAR(max) NULL DEFAULT NULL COLLATE 'French_CI_AS',
	PRIMARY KEY ("no")
)
;
